const data =[
    {
        id:"1",
        country:"Afghanistan"
    },
    {
        id:"2",
        country:"Albania"
    },
    {
        id:"3",
        country:"Algeria"
    },
    {
        id:"4",
        country:"Andorra"
    },
    {
        id:"5",
        country:"Angola"
    },
    {
        id:"6",
        country:"Antigua and Barbuda"
    },
    {
        id:"7",
        country:"Argentina"
    },
    {
        id:"8",
        country:"Armenia"
    },
    {
        id:"9",
        country:"Australia"
    },
    {
        id:"10",
        country:"Austria"
    },
    {
        id:"11",
        country:"Azerbaijan"
    },
    {
        id:"12",
        country:"Bahamas"
    },
    {
        id:"13",
        country:"Bahrain"
    },
    {
        id:"14",
        country:"Bangladesh"
    },
    {
        id:"15",
        country:"Barbados"
    },
    {
        id:"16",
        country:"Belarus"
    },
    {
        id:"17",
        country:"Belgium"
    },
    {
        id:"18",
        country:"Belize"
    },
    {
        id:"19",
        country:"Benin"
    },
    {
        id:"20",
        country:"Bhutan"
    },
    {
        id:"21",
        country:"Bolivia"
    },
    {
        id:"22",
        country:"Bosnia and Herzegovina"
    },
    {
        id:"23",
        country:"Botswana"
    },
    {
        id:"24",
        country:"Brazil"
    },
    {
        id:"25",
        country:"Brunei"
    },
    {
        id:"26",
        country:"Bulgaria"
    },
    {
        id:"27",
        country:"Burkina Faso"
    },{
        id:"28",
        country:"Burundi"
    },
    {
        id:"29",
        country:"Côte d'Ivoire"
    },
    {
        id:"30",
        country:"Cabo Verde"
    },
    {
        id:"31",
        country:"Cambodia"
    },
    {
        id:"32",
        country:"Cameroon"
    },
    {
        id:"33",
        country:"Canada"
    },
    {
        id:"34",
        country:"Central African Republic"
    },
    {
        id:"35",
        country:"Chad"
    },
    {
        id:"36",
        country:"Chile"
    },
    {
        id:"37",
        country:"China"
    },
    {
        id:"38",
        country:"Colombia"
    },
    {
        id:"39",
        country:"Comoros"
    },
    {
        id:"40",
        country:"Congo (Congo-Brazzaville)"
    },
    {
        id:"41",
        country:"Costa Rica"
    },
    {
        id:"42",
        country:"Croatia"
    },
    {
        id:"43",
        country:"Cuba"
    },
    {
        id:"44",
        country:"Cyprus"
    },
    {
        id:"45",
        country:"Czechia (Czech Republic)"
    },
    {
        id:"46",
        country:"Democratic Republic of the Congo"
    },
    {
        id:"47",
        country:"Denmark"
    },
    {
        id:"48",
        country:"Djibouti"
    },
    {
        id:"49",
        country:"Dominica"
    },
    {
        id:"50",
        country:"Dominican Republic"
    },
    {
        id:"51",
        country:"Ecuador"
    },
    {
        id:"52",
        country:"Egypt"
    },
    {
        id:"53",
        country:"El Salvador"
    },
    {
        id:"54",
        country:"Equatorial Guinea)"
    },
    {
        id:"55",
        country:"Eritrea"
    },
    {
        id:"56",
        country:"Estonia"
    },
    {
        id:"57",
        country:"Eswatini (fmr. 'Swaziland')"
    },
    {
        id:"58",
        country:"Ethiopia"
    },
    {
        id:"59",
        country:"Fiji"
    },
    {
        id:"60",
        country:"Finland"
    },
    {
        id:"61",
        country:"France"
    },
    {
        id:"62",
        country:"Gabon"
    },
    {
        id:"63",
        country:"Gambia"
    },
    {
        id:"64",
        country:"Georgia"
    },
    {
        id:"65",
        country:"Germany"
    },
    {
        id:"66",
        country:"Ghana"
    },
    {
        id:"67",
        country:"Greece"
    },
    {
        id:"68",
        country:"Grenada"
    },
    {
        id:"69",
        country:"Guatemala"
    },
    {
        id:"70",
        country:"Guinea"
    },
    {
        id:"71",
        country:"Guinea-Bissau"
    },
    {
        id:"72",
        country:"Guyana"
    },
    {
        id:"73",
        country:"Haiti"
    },
    {
        id:"74",
        country:"Holy See"
    },
    {
        id:"75",
        country:"Honduras"
    },
    {
        id:"76",
        country:"Hungary"
    },
    {
        id:"77",
        country:"Iceland"
    },
    {
        id:"78",
        country:"India"
    },
    {
        id:"79",
        country:"Indonesia"
    },
    {
        id:"80",
        country:"Iran"
    },
    {
        id:"81",
        country:"Iraq"
    },
    {
        id:"82",
        country:"Ireland"
    },
    {
        id:"83",
        country:"Israel"
    },
    {
        id:"84",
        country:"Italy"
    },
    {
        id:"85",
        country:"Jamaica"
    },
    {
        id:"86",
        country:"Japan"
    },
    {
        id:"87",
        country:"Jordan"
    },
    {
        id:"88",
        country:"Kazakhstan"
    },
    {
        id:"89",
        country:"Kenya"
    },
    {
        id:"90",
        country:"Kiribati"
    },
    {
        id:"91",
        country:"Kuwait"
    },
    {
        id:"92",
        country:"Kyrgyzstan"
    },
    {
        id:"93",
        country:"Laos"
    },
    {
        id:"94",
        country:"Latvia"
    },
    {
        id:"95",
        country:"Lebanon"
    },
    {
        id:"96",
        country:"Lesotho"
    },
    {
        id:"97",
        country:"Liberia"
    },
    {
        id:"98",
        country:"Libya"
    },
    {
        id:"99",
        country:"Liechtenstein"
    },
    {
        id:"100",
        country:"Lithuania"
    },

]

export default data